# Harsh parashar auto deloy
name: CI/CD to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:

    
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: YOUR_EC2_IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker rm -f $(docker ps -aq) || true
            docker pull harshdocker608/devops-app
            docker run -d -p 3000:3000 harshdocker608/devops-app